#Variables to create the table for the hospice (hs) pre-esrd claims from 
#2011-2016. Pre-esrd claims in USRDS are kept in files specific to the year. 

# the order of these files matters.
# use 2012 to create the postgres table and then add the other years to it
filenames_esrd =
  c(
    "preesrd5y_hs_clm_inc2012",
    "preesrd5y_hs_clm_inc2013",
    "preesrd5y_hs_clm_inc2014",
    "preesrd5y_hs_clm_inc2015",
    "preesrd5y_hs_clm_inc2016",
    "preesrd5y_hs_clm_inc2017",
    "preesrd5y_hs_clm_inc2011"
  )
#####fieldnames####
fieldnames_esrd = c(
  "USRDS_ID",
  "CDTYPE",
  "CLM_AMT",
  "CLM_TOT",
  "DPOADMIN",
  "DPODOSE",
  "DPOCASH",
  "DIALCRC",
  "DIALCASH",
  "DIALREVC",
  "DIALSESS",
  "DISCSTAT",
  "EPOADMIN",
  "EPODOSE",
  "EPOCASH",
  "HCFASAF",
  "HCRIT",
  "HGB",
  "PDGNS_CD",
  "PRM_PYR",
  "PROVUSRD",
  "PRPAYAMT",
  "RXCAT",
  "SEQ_KEYC",
  "ATTENDING_PHYS",
  "OPERATING_PHYS",
  "OTHER_PHYS",
  "masked_CLM_FROM",
  "masked_CLM_THRU",
  "masked_HSPCSTRT",
  "incident_year"
)
####column types #####
columns_esrd_2015 = cols(
  ATTENDING_PHYS = col_double(),
  CLM_AMT = col_double(),
  CLM_TOT = col_double(),
  DRG_CD = col_double(),
  DIALCRC = col_double(),
  DIALSESS = col_double(), 
  DPODOSE = col_double(),
  DIALREVC = "c",
  DISCSTAT = "c",
  EPODOSE = col_double(),
  EPOADMIN = col_double(),
  HCFASAF = "c",
  HCRIT = col_double(),
  HGB =col_double(),
  masked_HSPCSTRT=col_double(),
  masked_CLM_THRU = col_double(),
  masked_CLM_FROM = col_double(),
  OPERATING_PHYS = col_double(),
  OTHER_PHYS = col_double(),
  PER_DIEM = col_double(),
  PDGNS_CD = "c",
  PROVUSRD = col_double(),
  PRPAYAMT = col_double(),
  PRM_PYR = "c",
  randomOffsetInDays = col_double(),
  RXCAT = "c",
  SEQ_KEYC = "c",
  TDEDAMT = col_double(),
  TYPE_OF_BILL = col_double()
)
####column types #####
columns_esrd = cols(
  ATTENDING_PHYS = col_double(),
  CDTYPE = "c",
  CLM_AMT = col_double(),
  CLM_TOT = col_double(),
  DRG_CD = col_double(),
  DIALCRC = col_double(),
  DIALSESS = col_double(), 
  DPODOSE = col_double(),
  DIALREVC = "c",
  DISCSTAT = "c",
  EPODOSE = col_double(),
  EPOADMIN = col_double(),
  HCFASAF = "c",
  HCRIT = col_double(),
  HGB =col_double(),
  masked_HSPCSTRT=col_double(),
  masked_CLM_THRU = col_double(),
  masked_CLM_FROM = col_double(),
  OPERATING_PHYS = col_double(),
  OTHER_PHYS = col_double(),
  PER_DIEM = col_double(),
  PDGNS_CD = "c",
  PROVUSRD = col_double(),
  PRPAYAMT = col_double(),
  PRM_PYR = "c",
  randomOffsetInDays = col_double(),
  RXCAT = "c",
  SEQ_KEYC = "c",
  TDEDAMT = col_double(),
  TYPE_OF_BILL = col_double(),
  TYPE_ADM = col_double()
)